GET http://localhost:3001/api/accounts


###
GET http://localhost:3001/api/accounts/1



###
GET http://localhost:3001/api/accounts/1/transactions?page=1&limit=2



###
POST http://localhost:3001/api/accounts/1/transactions
content-type: application/json

{
   "type": "DEPOSIT",

    "amount": 2000,

    "description": "This is just a test"
}
